Tweaked and added image grid component
InfinitePixel/riot-toolbox pull request #3
Opened 2017-09-19 14:12 UTC by TaylorHorn

![screen shot 2017-09-19 at 10 12 05 am](https://user-images.githubusercontent.com/8713669/30596746-0bd25c9e-9d23-11e7-8b82-c148c3f2ec2e.png)

2017-09-19 14:20 UTC, MattStopa requested changes

2017-09-19 14:20 UTC, MattStopa commented on src/tags/rtb-image-grid/index.html
> +        font-family: 'Work Sans', sans-serif;
You can't set the the font family int he tag itself.

2017-09-19 14:20 UTC, MattStopa commented on src/tags/rtb-image-grid/rtb-info-box.tag
> +    .mydiv0 {
mydiv is a bad name. Needs to be more generic.

2017-09-19 14:20 UTC, MattStopa commented on src/tags/rtb-image-grid/rtb-info-box.tag
> +  <script>
random empty script tag

2017-09-19 14:20 UTC, MattStopa commented on src/tags/rtb-image-grid/rtb-info-box.tag
> +        <h3>TECH HIGHLIGHTS</h3>
Why is this stuff hard coded?

2017-09-21 15:41 UTC, TaylorHorn commented
![screen shot 2017-09-21 at 11 40 41 am](https://user-images.githubusercontent.com/8713669/30704786-c150e2da-9ec1-11e7-8149-7f5fabb3af9d.png)

2017-09-22 19:51 UTC, merged